### ISSUE TITLE
space shouldn't cause weirdness with NaN and going to the end of the textarea

### ISSUE THREAD

**Issue by KatyaAplonova** [jonorthwash/ud-annotatrix#188] opened 2017-12-08 18:51 UTC
When you are editting a comment in the textarea ,for example ```# labels = blah foo``` then the cursor goes to the end of the text area. and makes a newline for every character. this is non-optimal and should be fixed.

**Comment by jonorthwash** [comment] 2017-12-23 03:51
Is this a duplicate of #129?

**Comment by keggsmurph21** [comment] 2018-07-24 02:33
old, closing

**Closed by keggsmurph21** 2018-07-24 02:33 UTC
