### ISSUE TITLE
Add support for specifying a dependency relation when you make a new arc

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#38] opened 2017-06-22 17:12 UTC
When you make a new arc, you should have the opportunity to specify a dependency relation at the same time. The way I think it should work is as follows:

1) You click on the head,
2) A side bar appears with a complete list of the dependency relations where each relation has a hot key, like **a**cl, ad**v**cl, amo**d** -- they should be listed in alphabetical order of hot key.
3) You click on the dependent
4) You type the letter of the hot key and the relation is added.

Open question: where does the focus stay: on the head or on the dependent ? If on the head, how do you move it to a new head?

@fginter, is this more or less how you described before?

**Comment by jonorthwash** [comment] 2017-06-22 17:26
Duplicate of #3 .

**Closed by jonorthwash** 2017-06-22 17:26 UTC
