### ISSUE TITLE
DEL does not work in Safari

### ISSUE THREAD

**Issue by fginter** [jonorthwash/ud-annotatrix#98] opened 2017-09-20 11:59 UTC
Safari on a Mac does not react to "Cmd+backspace" which is the way to type DEL. Since Mac's don't have a DEL button, maybe backspace would be better? Found by @jnivre

**Comment by fginter** [comment] 2017-09-20 12:01
.... turns out it is Fn+backspace ... But maybe backspace would still be better, or either delete or backspace would be OK. Many Mac users do not know how to type DEL.

**Comment by maryszmary** [comment] 2017-09-23 12:11
The problem is: `backspace` was used to unselect all the selected arcs at one time. (It was not documented on the help page, sorry about that).
So, to be able to use `backspace` in the same way as `del`, I need either to assign another key to the function `backspace` was performing or remove it. @ftyers @jonorthwash what do you think?

**Comment by ftyers** [comment] 2017-09-23 14:43
Unselect all nodes could be just `escape`. I guess usually it's the case that you want to do that when you've clicked on stuff that you didn't want to click on and are trying to get back to the original state...

**Comment by maryszmary** [comment] 2017-09-25 18:26
Reassigned the keys: now `del` and `backspace` are for deleting, `esc` is for unselecting the arcs.

**Closed** 2017-09-25 18:35 UTC

**Comment by jonorthwash** [comment] 2017-10-14 02:48
In which revision?
