### ISSUE TITLE
help  page

### ISSUE THREAD

**Issue by arademaker** [jonorthwash/ud-annotatrix#100] opened 2017-09-20 12:17 UTC
do not describe how to zoom in/out.

**Comment by maryszmary** [comment] 2017-09-28 13:48
Unfortunately, there is no such option, as zoom the graph in\out, yet. But if you think, that such an option should be there, I can add it.
What do you think, @ftyers, @jonorthwash ?
E.g.: some checkbox, which enables zooming by scrolling, or some key combo, which acts like ctrl +/-, but only for the tree graph?

**Comment by ftyers** [comment] 2017-09-28 14:08
I think we should add a new issue for adding zoom functionality and close this issue as a duplicate of that one. I'm not sure which method I like better but maybe ctrl+shift+ -/+ like how to copy/paste in gnome terminal.

**Comment by jonorthwash** [comment] 2017-09-28 21:41
> I think we should add a new issue for adding zoom functionality and close this issue as a duplicate of that one.

Lol, could make sense.

**Comment by ftyers** [comment] 2017-10-13 17:57
Renaming issue to #116.

**Closed by ftyers** 2017-10-13 17:57 UTC
Labels: display of graphs, enhancement
