### ISSUE TITLE
Unable to delete arcs

### ISSUE THREAD

**Issue by JPJPJPOPOP** [jonorthwash/ud-annotatrix#205] opened 2018-01-03 04:04 UTC
Currently, I am unable to delete arcs. I cntrl clicked and highlighted some arcs, but upon hitting delete, the arcs unselect, but are still there. Tested on both Firefox and Chrome.

Believe #202 broke it. I reset back to #201 and it works again.
 
Because my Firefox browser allows hitting delete to go back a page, I sometimes accidentally exit the page when hitting delete even though I just selected some arcs.

**Comment by jonorthwash** [comment] 2018-01-04 06:21
@ftyers, @maryszmary, could one of you test this?

**Comment by gstark0** [comment] 2018-01-04 06:27
I confirm, I have also experienced this issue. Don't really know when this happens, but sometimes working on a sentence I can't remove deprels, I need to try to edit something or make another deprel and I can then remove them.

**Comment by maryszmary** [comment] 2018-01-04 19:31
I seem to have the problem both in chromium and firefox, but only after I press `ESC`. After reloading the page, the problem fixes. I guess, the problem might be related to #202.

**Comment by maryszmary** [comment] 2018-01-04 19:49
Yes, I think, the problem is caused by #202 and affects not only deleting the arcs, but also any key combinations (e.g. merging two tokens into a supertoken by pressing `s`). When I comment out the code added in #202, the problem seems to fix for me.

I'm not sure of the exact reason right now, but I commented out the code from #202 and wrote an alternative solution of #190, and now it works for me. @JPJPJPOPOP @jonorthwash @ftyers, please tell if the problem is fixed for you, if you had it before.

**Comment by gstark0** [comment] 2018-01-04 19:50
@maryszmary that was my first solution, but i changed it because it exited full screen mode on safari on Mac, so the preventDefault(); was quiet useful here.

**Comment by maryszmary** [comment] 2018-01-04 21:57
I see. I use linux and never tested it in safari. :)
But doesn't this help then?
```
if (key.which == ESC) {
        key.preventDefault();
        drawTree();
    };
```

(just inside an if-loop, as opposed to binding another handler inside of a function which is an event handler itself)

**Comment by maryszmary** [comment] 2018-01-04 21:58
@gstark0, just committed, could you test?

**Comment by gstark0** [comment] 2018-01-05 12:40
@maryszmary Doesn't work unfortunately :(

**Comment by maryszmary** [comment] 2018-01-05 23:39
@gstark0 Hmm... I'm afraid that I can't debug it, because I have problems running safari on linux. :(
Could you then try and fix the bug for safari, firefox and chromium together?

**Comment by gstark0** [comment] 2018-01-06 07:06
@maryszmary sure, I was going to suggest it :)

**Closed** 2018-01-28 17:32 UTC
