### ISSUE TITLE
Add support for saving file

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#21] opened 2017-03-23 14:41 UTC
Add support for saving/exporting the treebank. This should be lossless, in the sense that comments, order, etc. should be preserved.

**Comment by jonorthwash** [comment] 2017-03-29 06:01
Duplicate of #7.  If it doesn't work, reopen that issue, or if it's found to be missing features, file new issues.

**Closed by jonorthwash** 2017-03-29 06:01 UTC
