### ISSUE TITLE
Chat window should be minimised by default

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#325] opened 2018-09-25 21:41 UTC
Or even just disabled until enabled. It clutters up the interface.

**Comment by jonorthwash** [comment] 2018-10-01 03:30
I had specifically asked for this, and @keggsmurph21 implemented it; this must be a recent regression.

**Comment by jonorthwash** [comment] 2019-04-22 21:43
`bundle.js` wasn't updated in #342, so this issue remains unresolved.

**Comment by jonorthwash** [comment] 2019-04-24 17:02
@yaskevich, any update on this issue?

**Comment by yaskevich** [comment] 2019-04-25 21:46
It's a problem to make a bundle, because the build system of the project is outdated, its config should be completely rewritten.  I've made a build script for client JS and regenerate the bundle, it seems to work properly (chat windows is closed).
However,  I've just changed some parts of the code base, which is to be reviewed as a whole. 
New bundle is in PR #348.

**Comment by jonorthwash** [comment] 2019-04-25 22:37
So the script is just a short-term solution and that's why you didn't include it in the PR?

**Comment by yaskevich** [comment] 2019-04-26 17:17
Not exactly, rather because I fixed only task for client UI, not those for everything. Except of this, all this stuff must be properly tested, at least manually. But when I go that deeper, it stops looking like code challenge, but rather full-fledged project development. And just during this week I am under the pressure of several deadlines, which makes switching to additional tasks superhard.

**Comment by jonorthwash** [comment] 2019-04-26 18:32
@yaskevich, that's fine about how busy you are and the extent of work—I understand and am in a similar situation currently.  But I want to make sure I understand everything correctly, so I'm going to list what I am understanding and ask for you to correct these statements:
1. You wrote a script to generate a new `bundle.js`?
2. You didn't commit this new script because it's a temporary solution?
3. You don't have time right now to work on the build system (understood).
4. You suspect that `bundle.js` may not have been generated correctly, so you think it should be tested more thoroughly.

**Comment by yaskevich** [comment] 2019-04-28 13:56
Yes.
And today I've pushed to the same PR #348 completely rewritten Gulp config (in the syntax of current Gulp 4).

**Comment by jonorthwash** [comment] 2019-06-01 22:24
I merged the PR and it seems good now.

**Closed by jonorthwash** 2019-06-01 22:24 UTC
Labels: general interface
