### ISSUE TITLE
Undo doesn't work as expected

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#177] opened 2017-11-08 14:13 UTC
From Kadri: 

> As for bugs - on Francis' server I just managed to mess up a sentence in a file I used for exploring the program and the 'undo' button seems not to work. It works ok for text, but not for the visualized tree.

**Comment by jonorthwash** [comment] 2017-11-08 20:58
Can we merge this into the Undo metabug (#171)?

**Comment by jonorthwash** [comment] 2017-11-08 20:59
duplicate of #171

**Closed by jonorthwash** 2017-11-08 20:59 UTC
