### ISSUE TITLE
two lines between each sentence

### ISSUE THREAD

**Issue by mdelhoneux** [jonorthwash/ud-annotatrix#104] opened 2017-10-11 14:02 UTC
Hi guys, thanks for the great work!
When I upload a conll file with one line between each sentence and then use export corpus, I get a file with 2 lines between each sentence. Is there a reason for this or is it a bug?

**Comment by ftyers** [comment] 2017-10-11 15:41
This sounds like a bug, thanks for reporting it, we'll look into it :)

**Comment by ftyers** [comment] 2017-10-11 15:55
Hmm, we have been unable to reproduce it. Could you let us know which browser/OS you are using and give us a link to the treebank sample you are trying to import / export ?

**Comment by mdelhoneux** [comment] 2017-10-11 16:14
I'm using Chrome on ubuntu 14.04. I'll send you the sample via email (it's a student exercise ;))

**Comment by ftyers** [comment] 2017-10-11 17:10
Ooops, I didn't mean to close it. Miryam could you try the latest version. I think I've found/fixed the bug.

**Comment by mdelhoneux** [comment] 2017-10-12 07:26
Tried and approved, thanks a lot!

**Closed** 2017-10-12 07:26 UTC

**Comment by rueter** [comment] 2017-10-12 09:12
Hi, I am trying to use Firefox 52.4.1 (64-bit) and Chrome 61.0.3163.100 (Official Build) (64-bit) on OSX 10.10.5.
Firefox has a browse button that I can choose my file with. 
1) I discard the previous corpus with the <Discard corpus> button
2) browse and select a file with 3 commented lines followed by a conllu-formated sentence AND a blank line:
<example>
#sent_id = chapID01:paragID1:sentID1                                                                                                         
# text = Кечаень сыргозтизь налкставтыця карвот .                                                                                            
# text[eng] = Kechai was awoken by annoying flies.                                                                                           
1       Кечаень Кечай   N       N       Sem/Ant_Mal|Prop|SP|Gen|Indef   2       obj     _       Кечаень                                      
2       сыргозтизь      сыргозтемс      V       V       TV|Ind|Prt1|ScPl3|OcSg3 0       root    _       сыргозтизь                           
3       налкставтыця    налкставтомс    PRC     Prc     V|TV|PrcPrsL|Sg|Nom|Indef       4       amod    налкставтыця                         
4       карвот  карво   N       N       Sem/Ani|N|Pl|Nom|Indef  2       nsubj   _       карвот                                               
5       .       .       CLB     CLB     CLB     2       punct   _       .                                                                    
                                                                                                                                             
</example>

The data uploaded is not consistent:

Only one of the commented lines from the third sentence appears as the first sentence.
the second sentence is from line 912 of my document it too is commented

The first time I get what looks like text without conllu formating is 
<example>
#sent_id = chapID05:paragID8:sentID1
# text = — Виде . . . Пекшенень . . . — моткодезевсь бодясь , — инжеть састь . . .
# text[eng] = That's right... the Pekshes..., the old man muttered, are having guests.
</example>
where the machine grabs:
Пекшенень
as its own input line.

**Comment by jonorthwash** [comment] 2017-10-14 02:47
Which revisions fixed this?

**Comment by mdelhoneux** [comment] 2017-10-15 12:38
I'm guessing 5e0cfe18c67d810bc932b5e1d3c5b191be651249 but Fran could confirm, @ftyers ?

**Comment by ftyers** [comment] 2017-10-15 12:42
Yep. that looks like it, thanks @mdelhoneux ! :)
