### ISSUE TITLE
Can't tell direction of label if there are many to one node

### ISSUE THREAD

**Issue by ftyers** [jonorthwash/ud-annotatrix#94] opened 2017-09-19 09:52 UTC
In brat you can have e.g. `nmod>` or `<nmod`,  to show the direction of the arc in the label. We could use something like ◂  and  ▸  symbols

**Comment by maryszmary** [comment] 2017-09-23 11:42
Duplicate of #62.

**Closed** 2017-09-23 11:44 UTC
Labels: duplicate
